// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetCollection():Promise<Array<main.CollectionItem>>;

export function GetCollectionValue():Promise<string>;

export function GetWantlist():Promise<Array<main.WantlistItem>>;

export function Search(arg1:string):Promise<Array<main.SearchResult>>;
