// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddToCollection(arg1) {
  return window['go']['main']['App']['AddToCollection'](arg1);
}

export function AddToWantlist(arg1) {
  return window['go']['main']['App']['AddToWantlist'](arg1);
}

export function GetCollection() {
  return window['go']['main']['App']['GetCollection']();
}

export function GetCollectionValue() {
  return window['go']['main']['App']['GetCollectionValue']();
}

export function GetWantlist() {
  return window['go']['main']['App']['GetWantlist']();
}

export function Search(arg1) {
  return window['go']['main']['App']['Search'](arg1);
}
