// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCollection() {
  return window['go']['main']['App']['GetCollection']();
}

export function GetCollectionValue() {
  return window['go']['main']['App']['GetCollectionValue']();
}
